# Generated by Django 5.1.2 on 2024-10-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(upload_to='images/')),
                ('pname', models.CharField(max_length=200)),
                ('psize', models.TextField(max_length=15)),
                ('punit', models.TextField(max_length=50)),
                ('pdescription', models.TextField(max_length=1000)),
            ],
        ),
    ]
