# Generated by Django 5.1.2 on 2024-10-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdetail',
            name='pimage',
        ),
    ]
