# Generated by Django 5.1.2 on 2024-10-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0004_product_delete_pdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='sneaker1.jpg', upload_to=''),
        ),
    ]
