# Generated by Django 5.1.2 on 2024-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0005_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField(max_length=250)),
            ],
        ),
    ]
