# Generated by Django 5.0.9 on 2024-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0007_alter_register_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
