# Generated by Django 5.0.9 on 2024-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0008_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pprice', models.TextField(max_length=10, null=True)),
                ('psize', models.TextField(max_length=15)),
                ('punit', models.TextField(max_length=50)),
                ('pdescription', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
