# Generated by Django 5.0.9 on 2024-10-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0009_pdetail_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
