# Generated by Django 5.0.9 on 2024-10-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0010_login_alter_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
