# Generated by Django 5.0.9 on 2024-10-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapk', '0011_rename_name_register_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pprice', models.TextField(max_length=10, null=True)),
                ('psize', models.TextField(max_length=15)),
                ('punit', models.TextField(max_length=50)),
                ('pdescription', models.TextField(max_length=1000)),
            ],
        ),
    ]
